### ISSUE TITLE
Redirection to registration form fails (e.g. when a profile field is required) with version 2

### ISSUE THREAD

**Issue by benjaminfrombe** [humhub/auth-linkedin#6] opened 2024-09-03 14:07 UTC
I would like to use linkedin authentication combined with the user filling in extra information while registering. Is this possible ?
e.g. When I try now adding a required field like "Role", I get a registration error ...

**Comment by luke-** [comment] 2024-09-03 14:44
It should actually work like this. 
If a required profile field is missing, it is explicitly prompted.

**Comment by luke-** [comment] 2024-09-03 14:45
Can you test this with other AuthClients e.g. Google/GitHUb?

**Comment by benjaminfrombe** [comment] 2024-09-04 07:59
I have the same problem with Google OAuth ... 

FYI, this is the profile field "Role" config:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/eafc7804-4cdd-48f3-b71b-88fbb56c0448">

**Comment by luke-** [comment] 2024-09-04 09:26
Ok thanks for testing.

Can you please create an issue for this in the “humhub/humhub” repository. Seems to be a general AuthClient problem.

**Comment by marc-farre** [comment] 2024-10-10 11:15
@benjaminfrombe @luke- fixed in PR https://github.com/humhub/auth-linkedin/pull/8

The issue is when using v2 only (v1 doesn't work for me, maybe because of my recent LinkedIn auth app).

Error message:
```
Serialization of 'Closure' is not allowed
```

The issue was because of `ArrayHelper::getValue()` returning a Closure Object of LinkedinAuthV2, which was not serializable when writing the `authClient` to the session: https://github.com/humhub/humhub/blob/cb8e56c45051b6a7a179da07a3712fde0f9f5c81/protected/humhub/modules/user/controllers/AuthController.php#L242-L242

As a result, after redirecting to `/user/registration` the `authClient` from the session is empty: https://github.com/humhub/humhub/blob/cb8e56c45051b6a7a179da07a3712fde0f9f5c81/protected/humhub/modules/user/controllers/RegistrationController.php#L91-L91

I haven't tested other clients (such as Google), but they don't use `ArrayHelper::getValue()`, so if Google doesn't work either, it must be a different issue. But it is not a general AuthClient problem.

**Closed as completed** 2024-10-11 10:21 UTC

**Comment by luke-** [comment] 2024-10-11 10:23
@marc-farre Thanks!
